apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moviehub
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Petro1027/moviehub-e2e-devops.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: moviehub

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true