@baseUrl = http://localhost:5052
@movieId = replace-with-created-movie-id

### Health check - Get all movies
GET {{baseUrl}}/api/movies


### Get movies with pagination
GET {{baseUrl}}/api/movies?page=1&pageSize=2


### Search movies by title, director or genre
GET {{baseUrl}}/api/movies?search=nolan


### Get top rated movies
GET {{baseUrl}}/api/movies/top-rated


### Create movie
POST {{baseUrl}}/api/movies
Content-Type: application/json

{
  "title": "Blade Runner 2049",
  "director": "Denis Villeneuve",
  "genre": "Sci-Fi",
  "year": 2017,
  "rating": 8.0,
  "description": "A young blade runner discovers a secret that could change society."
}


### Get movie by id
GET {{baseUrl}}/api/movies/{{movieId}}


### Update movie
PUT {{baseUrl}}/api/movies/{{movieId}}
Content-Type: application/json

{
  "title": "Blade Runner 2049",
  "director": "Denis Villeneuve",
  "genre": "Sci-Fi",
  "year": 2017,
  "rating": 8.5,
  "description": "Updated description: a blade runner uncovers a secret connected to the past."
}


### Delete movie
DELETE {{baseUrl}}/api/movies/{{movieId}}


### Verify movie was deleted
GET {{baseUrl}}/api/movies/{{movieId}}